Updated

diff --git a/docker/docker/PKGBUILD b/docker/docker/PKGBUILD
--- a/docker/docker/PKGBUILD
+++ b/docker/docker/PKGBUILD
@@ -1,7 +1,7 @@
 # Maintainer: Sébastien "Seblu" Luttringer
 
 pkgname=docker
-pkgver=19.03.5
+pkgver=19.03.9
 pkgrel=1
 epoch=1
 pkgdesc='Pack, ship and run any application as a lightweight container'
@@ -18,21 +18,26 @@ options=('!strip' '!buildflags')
 # Use exact commit version from Dockerfile, see them in:
 # https://github.com/docker/docker-ce/blob/master/components/engine/hack/dockerfile/install/
 _TINI_COMMIT=fec3683b971d9c3ef73f284f176672c44b448662
-_LIBNETWORK_COMMIT=3eb39382bfa6a3c42f83674ab080ae13b0e34e5d
+_LIBNETWORK_COMMIT=0941c3f409260d5f05cfa6fc68420d8ad45ee483
+_APP_TAG='v0.9.0-beta1'
 source=("git+https://github.com/docker/docker-ce.git#tag=v$pkgver"
         "git+https://github.com/docker/libnetwork.git#commit=$_LIBNETWORK_COMMIT"
         "git+https://github.com/krallin/tini.git#commit=$_TINI_COMMIT"
         "git+https://github.com/spf13/cobra.git"
+        "git+https://github.com/docker/buildx.git"
+        "git+https://github.com/docker/app.git#tag=$_APP_TAG"
         'capabilities.patch'
         'disableresolution.patch'
         "$pkgname.sysusers")
-sha224sums=('SKIP'
+sha256sums=('SKIP'
             'SKIP'
             'SKIP'
             'SKIP'
             'SKIP'
             'SKIP'
-            '4c19a66617d73adf1c0b4b0a63e22cba296fd5af32b9b32a9787ff8d')
+            'SKIP'
+            'SKIP'
+            '541826011a9836d05a2f42293d5f1beadf2ca8d89fb604487d61a013505678eb')
 
 prepare() {
   sed -i 's,/var/run,/run,' docker-ce/components/engine/contrib/init/systemd/docker.socket
@@ -58,7 +63,7 @@ _fake_gopath_popd() {
 
 build() {
   ### check my mistakes on commit version
-  msg2 'Checking commit mismatch'
+  echo 'Checking commit mismatch'
   (
   local _cfile
   for _cfile in tini proxy; do
@@ -70,7 +75,7 @@ build() {
     _pkgbuild=_${_commit}_COMMIT
     _dockerfile=${_commit}_COMMIT
     if [[ ${!_pkgbuild} != ${!_dockerfile} ]]; then
-      error "Invalid $_commit commit, should be ${!_dockerfile}"
+      echo "Invalid $_commit commit, should be ${!_dockerfile}" >&2
       err=$(($err + 1))
     fi
   done
@@ -82,13 +87,26 @@ build() {
   export PATH="$GOPATH/bin:$PATH"
 
   ### cli
-  msg2 'Building cli'
+  echo 'Building cli'
   _fake_gopath_pushd docker-ce/components/cli github.com/docker/cli
   DISABLE_WARN_OUTSIDE_CONTAINER=1 make VERSION=$pkgver-ce dynbinary
   _fake_gopath_popd
 
+  ### app cli plugin
+  echo 'Building app cli plugin'
+  _fake_gopath_pushd app github.com/docker/app
+  make dynamic
+  _fake_gopath_popd
+
+  ### buildx cli plugin
+  echo 'Building buildx cli plugin'
+  _fake_gopath_pushd buildx github.com/docker/buildx
+  go build -o bin/docker-buildx -ldflags "-X github.com/docker/buildx/version.Version=$(git describe --match 'v[0-9]*' --always --tags)-tp-docker -X github.com/docker/buildx/version.Revision=$(git rev-parse HEAD) -X github.com/docker/buildx/version.Package=github.com/docker/buildx -X main.experimental=1" ./cmd/buildx
+  go clean -modcache
+  _fake_gopath_popd
+
   ### daemon
-  msg2 'Building daemon'
+  echo 'Building daemon'
   _fake_gopath_pushd docker-ce/components/engine github.com/docker/docker
   DOCKER_GITCOMMIT=$(cd "$srcdir"/docker-ce && git rev-parse --short HEAD) \
     DOCKER_BUILDTAGS='seccomp journald apparmor' \
@@ -97,7 +115,7 @@ build() {
   _fake_gopath_popd
 
   ### docker man pages
-  msg2 'Building man pages'
+  echo 'Building man pages'
   mkdir -p src/github.com/spf13
   ln -rsfT cobra src/github.com/spf13/cobra
   # use docker-ce cli version because they mess up with man dir
@@ -106,13 +124,13 @@ build() {
   _fake_gopath_popd
 
   ### docker proxy
-  msg2 'Building docker-proxy'
+  echo 'Building docker-proxy'
   _fake_gopath_pushd libnetwork github.com/docker/libnetwork
   go build -ldflags='-linkmode=external' github.com/docker/libnetwork/cmd/proxy
   _fake_gopath_popd
 
   ### docker-init
-  msg2 'Building docker-init'
+  echo 'Building docker-init'
   _fake_gopath_pushd tini github.com/krallin/tini
   cmake .
   # we must use the static binary because it's started in a foreign os
@@ -157,6 +175,10 @@ package() {
   # man
   install -dm755 "$pkgdir/usr/share/man"
   cp -r man/man* "$pkgdir/usr/share/man"
+  # cli-plugins
+  cd "$srcdir"/src/github.com/docker
+  install -Dm755 app/bin/docker-app "$pkgdir/usr/lib/docker/cli-plugins/docker-app"
+  install -Dm755 buildx/bin/docker-buildx "$pkgdir/usr/lib/docker/cli-plugins/docker-buildx"
 }
 
 # vim:set ts=2 sw=2 et:
